### ISSUE TITLE
Lang: Add Julia Support

### ISSUE THREAD

**Issue by ajbonkoski** [ZeroCM/zcm#15]

**Comment by rdeits** [comment]
I've been using LCM from Julia for a while, and I have a couple of packages for working with it: 

https://github.com/rdeits/LCMCore.jl provides access to the publish and subscribe methods by using the LCM C API, and https://github.com/rdeits/PyLCM.jl provides message encoding and decoding via python (since there's no Julia `lcm-gen` yet). 

I've been considering switching those bindings to use ZCM under the hood, but I'm not sure how I would deal with handling messages asynchronously. LCMCore.jl uses the `lcm_get_fileno` to get the LCM file descriptor, which makes it easy to asynchronously watch for new messages in Julia, but that method isn't supported in ZCM. 

Is there some alternative to the LCM file descriptor in ZCM?

**Comment by olsoni** [comment]
Unfortunately there is not a way to access the underlying file descriptor in zcm. ZCM is transport-agnostic, therefore it can't guarantee that an underlying transport will even *have* a simple file descriptor to hand to the user. Because of this difficulty, we added the api-level functions `zcm_start()` and `zcm_stop()` to allow the user to start up a thread that handles messages asynchronously.

Unfortunately, this doesn't work for Julia..... at all ... I actually was just working on Julia support within zcm last week (see the partially finished `core-julia_support` branch) and ran into some snags. Julia only allows callbacks to be triggered in the main REPL thread (and crashes if anything triggers a callback in a different thread). There is a way to get around this by triggering the asynchronous scheduler, but the work around seems like it won't play nice with synchronously handled messages. 

As a potential improvement to the core zcm bindings, we've been considering adding a `zcm_message_ready` function that would call down into whichever transport was being used so the user could know when `zcm_handle` would result in a callback being triggered.

If you want to chat about any of these ideas or have any other zcm related questions, feel free to hop on our Gitter and give us a ping (https://gitter.im/ZeroCM/zcm).

**Comment by jbendes** [comment]
Implemented in https://github.com/ZeroCM/zcm/pull/163.  Will hopefully be merged next week

**Comment by olsoni** [comment]
merged "next week" #163

**Comment by jbendes** [comment]
Merged and in use for a while now
