### ISSUE TITLE
Implementation-dependent and undefined behavior of bit shifts in hashUpdate

### ISSUE THREAD

**Issue by tkoolen** [ZeroCM/zcm#157]
See https://github.com/lcm-proj/lcm/issues/198.

**Comment by jbendes** [comment]
Hey @tkoolen let me know what you think of this https://github.com/ZeroCM/zcm/pull/158

**Comment by tkoolen** [comment]
Yep, that makes sense to me. You may want to update [the docs](https://github.com/ZeroCM/zcm/blame/master/docs/zcmtypesys.md#L107-L145) as well. Also, just grep for `int64_t` to find a bunch of other hash uses like

https://github.com/ZeroCM/zcm/blob/60a11d2b60edb019fd137644f1320bbcd6a8f2f6/examples/cpp/CustomIndexerPlugin.cpp#L30

that should be changed.

**Comment by jbendes** [comment]
Ahhh the docs. Good catch. I actually think we should leave the hash as int64_t since all fields in zcmtypes are signed. There is no such thing as an unsigned integer in some languages and zcmtypes (and lcmtypes) don't support unsigned integers. I think we should leave the hash as signed and just ensure that it is unsigned whenever we do math on it.

**Comment by tkoolen** [comment]
OK, I buy that. Also search for `i64` as there is at least one more bad docs usage of that (maybe others).

**Comment by jbendes** [comment]
Okay I think i got em all. Also switch over zcm gen's emit java to use the unsigned bit shift operator `>>>` even though it shouldn't really matter. I'll wait for it to pass regression testing and then go ahead and merge it in. Thanks for catching that!

**Comment by jbendes** [comment]
Handled in https://github.com/ZeroCM/zcm/pull/158

**Comment by jbendes** [comment]
This issue has been reopened. We reverted the change on zcm/master since it actually changes the hashes of the generated types. The fix suggested in this issue is definitely the correct way to do it, but given that making the fix will invalidate all old logs, we need to make some tooling to transcode logs from the wrong hashes to the right hashes before merging. We'll make an email announcement so people know it's coming and then we'll plan on merging it soon

**Comment by jbendes** [comment]
Okay change of plans. Just implemented a defined, sign-extended, right bit shift in the hash generation. That way there is no change to the hashes generated on **most** machines and we get consistent and defined behavior when bit shifting for the hash generation.

**Comment by jbendes** [comment]
Did the above on https://github.com/ZeroCM/zcm/pull/160/commits/e9c7bfc401ea15aa64291507da37d1163e5506c0

**Comment by jbendes** [comment]
Handled in https://github.com/ZeroCM/zcm/pull/160
