### ISSUE TITLE
Move from asserts to error codes

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#244]
The `zcm.c` file contains many calls to `ZCM_ASSERT` and it seems like they are being used for error handling instead of checking for invariants. In most of those cases the asserts could be replaced by a return code. For example in [line 82](https://github.com/ZeroCM/zcm/blob/735d37539f64a72a45a49258ad6ba175838d8889/zcm/zcm.c#L82) returning `ZCM_EMEMORY` would be more appropriate. 

Also the many checks whether the transport is blocking (such as in [line 266](https://github.com/ZeroCM/zcm/blob/735d37539f64a72a45a49258ad6ba175838d8889/zcm/zcm.c#L266)) do not seem right to me. Those asserts are easily triggered  in any application designed with a blocking transport in mind. Just imagine launching it with the `ZCM_DEFAULT_URL` environment variable set to a a non-blocking transport. In all cases where we check for the transport to be blocking, the following line calls one of the `zcm_blocking_*` functions. Maybe we should move this check inside the constructor of `zcm_blocking_t`? This way we catch the wrong configuration way earlier and we save some overhead.

The same can be said about the checks for `ZCM_NONBLOCKING`. The corresponding assert could just be moved to `zcm_nonblocking_create`.

I would be happy to submit a pull request for this but I would be interested in your opinion before.

This issue might be related to #228, #99 #87 and  #155.

**Comment by jbendes** [comment]
@erniejunior generally we've used asserts more liberally than we probably should have. The asserts throughout zcm.c are there because if you're calling those functions accidentally with a blocking transport, you probably have to rewrite a bunch of the userspace code. Specifically, the thought was that if you were accidentally calling `zcm_start` on a nonblocking transport, you probably don't understand the difference between blocking and nonblocking transports. The `assert` is there to warn you that you probably don't understand a crucial aspect of `zcm` and you should stop and go read a bit more.

Specific to your first point about the out of memory assert, we do have an outstanding issue (albeit not a very well worded one) https://github.com/ZeroCM/zcm/issues/117 that aimed to address some of that. That should definitely be a handled error case and not an assert.

You are correct that the asserts are easily triggered if you call functions with improper arguments. That's kind of the point. If we get rid of all of those asserts, then we're pushing all of the error checking into user land instead of keeping it inside ZCM. In other words, I'm a fan of the loud ASSERT over the relatively quiet return variable. But I can be persuaded with good reasoning

**Comment by erniejunior** [comment]
My point about removing the asserts from the start/stop/run functions was not to remove the asserts completely. Rather they can be moved to `blocking.cpp` and `nonblocking.c` and thereby reduced to just two asserts. It just results in far less clutter in the source code and makes it easier to read. I did this in [this feature branch](https://github.com/erniejunior/zcm/tree/feature/improve_c_error_handling) if you want to have a look.

I still have mixed feelings about the asserts on the transport type. As an application developer I might not have any control on what transport is being used. Therefore I should at least have the option to catch this error somehow. On the other hand I might just test myself what kind of transport I am dealing with before calling `zcm_start` and spawn a meaningful warning to the user.

**Comment by erniejunior** [comment]
Right now I am trying to introduce the `ZCM_EMEMORY` error codes and am a bit stuck on `zcm_create` (with similar problems showing up for other functions). Since it returns a pointer to a `zcm_t`, there is no way I can also return an error code. To make this possible I would need to change the signature from `zcm_t* zcm_create(const char* url)` to something like `int zcm_create(const char* url, zcm_t* z)` which would mean a significant change in the API (wmich you probably do not like because you want to be compliant with LCM).

If it were only for catching the memory errors I would be OK with just returning `NULL` instead. But there is a number of other reasons that a zcm context can not be created such a `""` URL without `ZCM_DEFAULT_URL` specified or a malformatted URL. What do you think? Should we instead extend the API with the new function signature?

**Comment by jbendes** [comment]
Yeah i mean asserts are 100% not the correct way to be handling all of this stuff. They were just a crutch until we had some time to go through and fix them. Your suggestion seems perfectly fine, and I'm not overly concerned about breaking LCM API compatibility anymore. But I will ask, why do you care about solving this specific issue? Seems relatively insignificant in all use cases of zcm that I've heard of. The style of transport allowed is chosen by which api the developer decides to support, and then all users must follow that. Setting `ZCM_DEBUG=1` helps diagnose things that go wrong during initialization (albeit they take down your program on assert). Just curious what use case has come up that warrants the effort into this type of stuff.

**Comment by erniejunior** [comment]
Great to hear that you not care about LCM API compatibility so much any more. This gives me some more freedom.

Initially I just wanted to fix #228. While I am at it I might as well fix more of the  smaller error handling issues in order to push the overall code quality of ZCM.

**Comment by olsoni** [comment]
Went over your branch and made some initial changes / comments. I think I like using the `zcm_try_...` function naming scheme for functions that might return error codes. Additionally, we'll need to go over some of your removed asserts a little more carefully because simply adding 1 assert in the construction of a blocking / nonblocking zcm instance won't catch cases where the user misuses the API (for instance, constructing a nonblocking zcm instance but then calling `zcm_resume` on it. Take a peak at the initial changes and I'll think more on those removed asserts.

**Comment by erniejunior** [comment]
Cool thanks a lot for the review! I like the `_try_` naming. I will go and double check if the semantics of the existing `*_try_*` functions matches the new meaning of "like the original but with error codes and no asserts".

I agree that I might have removed the ASSERTS too aggressively at first. We still want to catch all API abuse cases with them ...

Feel free to use the (I think somewhat newer) annotation features on the pull request. You can even commit code right to my PR-branch. If you do not like that, its OK too it just means some more juggling around with different remotes for both of us.

**Comment by erniejunior** [comment]
I just reviewed the different cases in which we use the `*_try_*` naming scheme. Unfortunately it is not quite consistent:
* In `flush/try_flush` it distinguishes between a blocking and a non-blocking version of flush.
* In `stop/try_stop` the only distinction is whether an error code is returned or not. Here I see no justification for the `stop` without any return value because the application developer can always just choose to ignore the return value.
* `(un)subscribe` and `try_(un)subscribe` are actually equal for non-blocking transports. For blocking transports the `*_try_*` variants disables waiting for the lock on the `subDispMutex` and the `subRecvMutex` which both seem to be related to not messing up the subscription lists. If the `*_try_*` variants can not get the lock, they just return `ZCM_EAGAIN`.
* The new `*_try_create*` functions that we just introduced are just variants of the original functions without asserts and with an error code.

**Comment by olsoni** [comment]
Agreed, the "_try_" naming convention has potentially been a bit over-used at this point. I believe the original intent was that anything with "_try_" would be a function that may or may not actually accomplish what you told it to do, but would return whether (and why) the operation succeeded or failed. This interpretation was nebulous enough that it could be interpreted as a nonblocking way to do otherwise blocking operations or (in the more recent case) to distinguish between functions that would assert vs returning an error. 

I'll pop over to #249 and we can continue the discussion there. @jbendes will want your input as well.

**Comment by erniejunior** [comment]
I think this one can be closed now?

**Comment by olsoni** [comment]
yup, resolved by #252
