### ISSUE TITLE
Proposal for lots of small changes

### ISSUE THREAD

**Issue by erniejunior** [ZeroCM/zcm#249]
I tried to get a better overview of the C API and how it is influenced by the support for embedded/PC targets and blocking/non-blocking transports. I came up with the following diagram. Are my assumptions correct here?
![api_overview](https://user-images.githubusercontent.com/1250234/57459252-28a1ab00-7273-11e9-9b91-d43f8642d3f6.png)

Based on my reading, I would propose the following changes. Please let me know if you like some of them or not. Feel free to open separate issues if you think that individual points need more/a separate discussion. After we agreed on what to change and what to keep I will prepare a pull request.

1. Rename `try_flush` -> `flush_nonblock` (more descriptive name) **done**
1. Rename `zcm_create` -> `zcm_create_from_url` (more descriptive name) **done**
1. Rename `zcm_create_trans` -> `zcm_create_from_trans` (original name makes me think that this function creates a transport and not a zcm object) **done**
1. Remove `zcm_try_(un)subscribe` and implement `zcm_(un)subscribe` in a non-blocking way using a queue. (The `*_try_*` variants were basically the non-blocking variants of the function when blocking transports are used. The app-developer had to call subscribe again if it did not work. As an app-developer I do not expect subscribe/unsubscribe to be blocking at all)
1. remove `zcm_stop` and rename `zcm_try_stop` -> `zcm_stop`. Maybe keep `zcm_try_stop` for backwards compatibility and print a warning that it is deprecated. (They were basically equal to eachother to begin with except for the return code) **done**
1. Make the `*_try_create_*` functions (which return error codes instead of crashing on asserts  and only exist in my error codes feature branch) the default functions and rename the current defaults (with the asserts) to `lazy_create_*`. (It **is** lazy to not check for those errors. Lets at least call the app-developer names if he/she decides to ignore them anyways. The lazy variants could be used for quick testing/development.)
1. All functions in the embedded API should be structured like this:
    ```C
    ret_t function(zcm_t* zcm, ...) {
        #ifndef ZCM_EMBEDDED
        if(zcm->type == ZCM_BLOCKING) {
            // Handle blocking specific stuff
        } else {
        #endif
        
        #ifdef ZCM_EMBEDDED
        ZCM_ASSERT(zcm->type == ZCM_NONBLOCKING);
        #endif
        
        // Handle non-blocking specific stuff
        
        #ifndef ZCM_EMBEDDED
        }
        #endif
        
        // Handle stuff independent of blocking or non-blocking transport
        return ret;
    }
    ```
    (I do not like the current structure where lots of non-reachable code is generated for the non-embedded variant)
1. Change type of `recev_utime` in the `zcm_recv_buf_t` to unsigned. (right now this generates compiler warnings and I think the compiler is right about it)
1. Change type of `data_size` in the `zcm_recv_buf_t` to size_t (same reason as above)
1. Remove return keywords from the ends of void functions. E.g. in `zcm-cpp-impl.hpp` (same reason as above) **done**
1. Strictly separate the ZCM core in two parts: 
    1. An inner core written exclusively in C89 with non-blocking transports. No mixing with C++ code. No `#ifndef ZCM_EMBEDDED`. Embedded-compatible out-of-the-box without any preprocessing scripts that prepend defines.
    1. An outer core which adds blocking transports. Implemented in C++ for convenience. This outer core might even not expose a C interface any more if we decide to drop that in #248.
    (This way we do not need all those preprocessor commands and weird build steps which modify the source code and selectively pack stuff in a tar file)

**Comment by olsoni** [comment]
Haha yeah you weren't kidding about the "lots of changes" part :)

I'll take a look into this stuff more closely, but on the surface, I think I could get on board with most of the proposed renames. For number 7, I'll probably have to write up an example and compare it side by side, but seems like we could definitely clean some of that up. 8-10 seem straightforward and fine, though for some languages that don't have unsigned integers, we'll have to be careful about how we wrap the recv_buf for them. 

For 11, we'll definitely want to see where we end up with #248, but this seems like a pretty large change which we'll want to approach with some caution to ensure we don't break any functionality along the way if we chose to go down this route. Definitely important to not remove the C bindings for a blocking api because all other languages use them.

**Comment by erniejunior** [comment]
Ok then I will prepare a PR with the trivial changes first including. 1-6 and 10 asap. Once that is merged we continue with looking at how well 7 goes in practice, then think about 8 and 9 and finally 11. Is that OK for your? Or should I wait with the first PR until looked more closely.

**Comment by olsoni** [comment]
For number 4 and 5, I'm maybe a little confused with what your intent is given that the (un)subscribe and stop functions will block until success for blocking transports. I definitely want to keep that as an option within the API. 

For the others, I want to get @jbendes input as well, but they all seem like pretty quick name changes, so it wouldn't hurt if you wanted to whip up a quick pullreq with those first. If you want to wait until after he chimes in, that's ok too.

**Comment by jbendes** [comment]
Sorry I haven't fully grasped the entire conversation so far. But at a high level, I'm a big fan of labeling the APIs inside `zcm.h` and `zcm-cpp.hpp`. Your diagram well illustrates how confusing the current state of affairs is haha. The `try` functions were written for 1 purpose (and they were never really intended to be called by users). They were added to the API because when writing bindings for certain single thread languages (like python, nodejs, etc), we needed a way to fail certain API calls so as to not cause a deadlock. 

An example:
Two threads, `A` and `B`. The `A` thread is the zcm handle thread. `B` thread is a user thread.
`A` thread receives a message and goes to dispatch to the message to all subscriptions waiting on it.
`B` thread simultaneously goes to add a new subscription.
It should be clear that both threads must grab the same lock so `B` thread can't add a subscription while `A` thread is looping through the subscriptions and calling all of them. That would be a data race. This also illustrates a current issue with `zcm` which is that you can neither unsubscribe nor subscribe from within a subscription callback as doing so would cause a deadlock.
Now imagine how this works in single threaded languages like node, python, julia, etc. 
The `A` thread receives a message to dispatch to all subscription callbacks. So `A` thread grabs the subscription list lock and starts calling callbacks. Since we're in a single threaded language, however, each callback must grab the main thread lock when it is called (the GIL in python, or libuv main thread in node and julia). So let's say thread `A` goes to grab that main thread lock, but blocks waiting on thread `B` (the main user thread) because the user is currently running code.
Meanwhile in thread `B`, the user calls `(un)subscribe` because they want to add or remove a subscription. `B` thread goes to grab the subscription lock, but is unable to do so because the `A` thread already has it. If `subscribe` is unable to return a failure, then `B` thread is stuck attempting and reattempting to grab a lock it will never be able to get because `A` has the subscription list lock and is waiting on the main thread lock, and `B` has the main thread lock and is waiting on the subscription list lock. Unless `(un)subscribe` is able to return an error and the user is able to try again after releasing and reacquiring the main thread lock, we will have created a deadlock.

So what we've done is abstract all of that confusion away inside the APIs of the languages that need that complexity, effectively hiding it entirely from the user.

I know that was long-winded, but I wanted to provide some context around why the `try` functions exist at all. I'm sure some of them can be combined with other functions in the API, but the intent was that regular users wouldn't ever have to call them. We can equally move all of the `try` functions to an `zcm_advanced.h` or `zcm_internals.h` file if that would clarify this at all.

**Comment by erniejunior** [comment]
Regarding 4:
To clarify my intent was to remove `zcm_try_(un)subscribe` and implement `zcm_(un)subscribe` in a non-blocking way. Thanks a lot to @jbendes to point out the many ways this can go wrong (concurrency is a hard topic after all)! Nonetheless I think I might find a way to implement it in a non-blocking way without deadlocks by not using mutexes in the first place. Right now we use a hash map containing lists to store the subscriptions. This is basically a multimap. If you look [here](http://kera.name/articles/2011/06/iterator-invalidation-rules/) you see that according to the C++ standard you can iterate multimaps while adding elements and when you remove an element you just need to get the lock to the element to be removed. This makes it a lot easier. Even if that were not the case, a workaround would be some kind of "to remove in the future" and "to add in the future" queues which get filled by the user thread when subscribe/unsubscribe is called and executed by the handler thread after iterating the list of subscriptions (or before).

Regarding 5:
I would like to remove `zcm_try_stop` and change the signature of `zcm_stop` from `void zcm_stop(zcm_t* zcm)` to `int zcm_stop(zcm_t* zcm)`.

**Comment by erniejunior** [comment]
Regarding 8 and 9: Apart from Julia (which seems to support unsigned types) no other language seems to explicitly seems to wrap the receive buffer. Is this assumption true? I just did a quick global search in the zcm repository.

**Comment by erniejunior** [comment]
Quick update:
1. done in #252 
1. done in #252 
1. done in #252 
1. Even though I think that in principle subscribe and unsubscribe should be non-blocking, in most real world use-cases this does not hurt because they are called rarely. I therefore decided to drop this point since the additional implementation effort and risk of introducing bugs are not worth it.
1. done in #252 but I think about undoing it. For some silly reason I had in mind that both variants of zcm_stop basically did the same with just a different function signature. This is not true and therefore the reason to remove zcm_try_stop disappears.
1. In hindsight I am hesitant to introduce the term `_lazy_` because it is misleading (in other contexts it is used when something is only created on demand which is not true here). We should rather promote the `zcm_try_create_*` variants in the documentation, examples and tests.

eleven. Done in #252

Please merge my PR soon so we can start thinking about the other issues.

**Comment by jbendes** [comment]
This is done, correct? Good to close out?

**Comment by erniejunior** [comment]
The points that are still open should go to separate issues. As soon as I created the separate issues I will close this one (keeping it open as a remainder for me).

**Comment by jbendes** [comment]
@erniejunior shall I close this out now?
