### ISSUE TITLE
Include package in type name when determining hash.

### ISSUE THREAD

**Issue by samueldaniel** [ZeroCM/zcm#334]
Problem: two identical types in different packages have identical hashes.
```
package foo;
struct do_thing {
  int64_t timestamp;
}
```
and
```
package bar;
struct do_thing {
  int64_t timestamp;
}
```

`zcm-gen` will create identical source code files for these two types. It would be great if `zcm-gen` hashed on the full name of `foo.do_thing` and `bar.do_thing`.

**Comment by jbendes** [comment]
I think the best route to doing this would be to include it a config parameter just like the "hash member names" and "hash type names" options. Like a "hash package name" option or something like that. Would also have to resolve how we handle packages specified on the command line for zcm-gen. Would they be treated the same way? All questions to answer as this one gets worked on

**Comment by jbendes** [comment]
Here is the gitter conversation where this came from: https://gitter.im/ZeroCM/zcm?at=60b6b25514d9cd234a6fd349

**Comment by jbendes** [comment]
So this is actually intended behavior. Currently the package name isn't used in the type hash calculation so that you can change what package a type is in on a per-user basis. That is to say that if developer 1 decides that they want type T inside package P1, but developer 2 wants type T inside package P2, they should still be able to send each other decodable messages. We can potentially make this behavior configurable the same way `./waf configure` allows for changing hashing behavior of other things.

**Comment by jbendes** [comment]
Without any response here, I'm going to close out this issue. Feel free to respond to open it back up
