### ISSUE TITLE
Python examples waiting one second between publishing messages

### ISSUE THREAD

**Issue by lhcubillos** [ZeroCM/zcm#354]
Hi! I'm new to ZCM (I come from LCM) and I've been working through the examples in both C++ and Python to understand the project. I saw that in all Python examples when you want to publish a message, the behavior is as follows:
```python
zcm.publish("CHANNEL",msg)
time.sleep(1)
zcm.publish("CHANNEL",msg)
```
I tried it on my computer, and only the second publish actually publishes the message. And if the sleep is not there, then the message is not published at all. Could you please explain that behavior?

Thank you!

**Comment by jbendes** [comment]
Hey Luis,

Welcome to the ZCM team! That's actually an interesting side-effect of using the `ipc` transport. It's just simply that the underlying library that implements the `ipc` transport (called `libzmq`) needs a moment to set up some filesystem resources after the first publish. So the first publish doesn't ever actually get sent - it only sets up the resources so that future messages get sent. This shouldn't matter in a "good" design as zcm is intended to be used in a "udp" manner in which delivery is never assumed to be guaranteed. That means you keep publishing the information you need someone to receive until it's no longer relevant. Make sense?

**Comment by lhcubillos** [comment]
Hi! Thank you for your quick response. That makes sense, thank you for the detailed answer. I thought that it was only happening in Python, and that was weird, but I just tested with C++ and it has the same behavior.

Thanks!
